name: tf3
channels:
  - conda-forge
dependencies:
  - astropy
  - autopep8
  - corner
  - dtaidistance
  - emcee
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - peakutils
  - python
  - tensorflow=2.10.0
  - spyder
