name: tf3
channels:
  - conda-forge
dependencies:
  - astropy
  - autopep8
  - corner
  - dtaidistance
  - emcee
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - peakutils
  - python
  - scikit-learn
  - spyder
  - tensorflow-gpu=2.11.0
  - ultranest
