name: blazarml
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - autopep8
  - dtaidistance
  - jupyter
  - matplotlib
  - keras-tuner
  - numpy
  - pandas
  - python
  - tensorflow-gpu>=2.11.0
  # - tensorflow>=2.11.0